/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bfa4a71d-85e4-46fa-9e1e-9ad96fbc39ec",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GNo8f7eLz",
    "aws_user_pools_web_client_id": "6k188odn5u4vbidvi60k7d8s6e",
    "oauth": {
        "domain": "kryptond755f99e-d755f99e-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://192.168.1.102:19000/",
        "redirectSignOut": "exp://192.168.1.102:19000/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://c4o5m7svxfg67en5n6dnyg6br4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
